Skip to content
Shop Morgan Hill
Delivery Area
Log In
0 items – $0.00



START or grow YOUR FLOCK!
Chick Season Begins FEBRUARY 2026
Pullets available late APRIL 2026
PULLET sales beginning MAY. Sales are on a first-come-first-serve basis. Pullets will be available until FALL.
Get baby chicks along with all the supplies you need to start your flock with us!
Our chicks will arrive beginning February 20th. Sales begin on Chick Days for each batch until we sell out.

See Availability
What You'll Need

Our first chicks of the season arrive February 20, 2026!

Availability, hatch dates, and breed information will be posted in January 2026.

Get your baby chicks — plus all the feed, brooders, heat lamps, and supplies you need to start your flock — right here in one stop.

Pullets will be available April/May 2026.
Our first Pullet Day will be announced in early April 2026.

All chick and pullet sales are first-come, first-served and available while supplies last.

Questions? We’re happy to help — please don’t hesitate to contact us.

*Chick sales may be limited on chick day depending on availability and customer demand. If demand is high (defined as 20 or more customers in line), we will temporarily limit purchases to ensure as many families as possible have an opportunity to buy chicks. If demand is not high, customers may purchase as many chicks as they wish.

*All chicks are sold on a first-come, first-served basis. We do not offer holds or reservations. However you may place special orders ahead of time.

*Baby chicks are FINAL SALE. Please remember they are only a few days old and are extremely delicate creatures. Unfortunately you can do EVERYTHING correctly and still lose them for unknown reasons.

*All chicks have been vaccinated for Marek

*Standard breeds are sexed however gender selection is about 90% accurate on average. Bantams and specialty breeds are NOT SEXED. If you get a STANDARD BREED rooster you may bring it back WITH PROOF OF PURCHASE. We are happy to help you rehome it. Bantams and specialty breed roosters WILL NOT BE taken back.

Chick Care Instructions
Chick FAQs
Batch Availability
Chicks will be sold on a first-come-first-serve basis on CHICK DAY 
Please note chick availability may change. Please check for updates after 6 PM a day before chick day. We do not have control over the breeds and amount of chicks we receive, but the hatchery has assured us that they are doing their best to fulfill orders.

We look forward to seeing you for our scheduled chick days:

February 20th
March 13th
April 3rd & 25th
May 13
June 3 & 24th
July 15th
August 5th
More details on breed availability below

Chicks will be available at both our San Jose location and Morgan Hill. We will begin giving numbers 10 mins prior to start time. No chicks will be sold before this time.

 

*** UPDATED 03/27/2026 @ 10:00AM ***
April 3rd 2026
*Breeds below will be confirmed when chicks arrive

 12PM San Jose
 1PM Morgan HIll
 

 Ameraucana- Female
Australorp -Female
Barnevelder Chicken - Female
Barred Rock - Female
Bielefelder Chicken - Female
Black Silkie Bantams - Not Sexed
Blue Silkie Bantams - Not Sexed
 Buff Silkie Bantams - Not Sexed
Delaware - Female
Easter Egger - Female
French Black Marans - Female
French Copper Marans - Female
Khaki Campbell Duck - Female
Lavender Orpington - Female
Light Brahama - Female
Mille Fleur D'uccles Bantams - Not Sexed
Olive Eggers - Female
Rhode Island Red- Female
Rouen Duck - Female
Salmon Faverolle - Female
Silver Laced Wyandotte- Female
Splash Silkie Bantams - Not Sexed
Welsummer Chicken - Female
White Pekin Duck - Female
White Silkie Bantams - Not Sexed
Browse
What You'll Need

Baby Chicks
Little Giant Mix and Match Feeders/Waters
Purina Medicated 5lb 25lb 50lb
Heat Lamp + Bulb
Chick Boost
Poultry Bedding
Manna Pro Grit with Probiotic

Organic Chicks
Scratch & Peck Starter Mash 10lb 25lb 40lb
Scratch & Peck Organic Herbs
Scratch & Peck Chick Grit
Glass Mason Jar Feeder/Water
Poultry Bedding
Heat Lamp

Pullets
Coops
Purina Flock Raiser or Organic Grower
Hen Boost
Oyster Shell
Grubs
Grit
Manna Pro Galvanized Feeder/Water
Delivery Options
View Gallery

Additional Products
If You'd like to Browse All of the Poultry Products We Offer, Click Below
All Chicken & Hen Products 
Gallery
Baby Chicks & Laying Hens




Delivery Area
Throughout the Bay Area
We delivery all around the Bay Area, contact us to schedule a delivery in your neighborhood

Livestock

Peninsula
Including Woodside, Portola, Atherton, Los Altos, Stanford, Menlo Park, and Palo Alto.

Deliveries: Thursday Weekly

* Orders must be placed by 12PM the day prior to your route


South Bay
Including South San Jose, Morgan Hill, San Martin, Gilroy, and Hollister.

Deliveries: Wednesday Weekly

* Orders must be placed by 12PM the day prior to your route


Small Pet

  
Shop San Jose 
Shop Morgan Hill 
Quick Links
Testimonials
Contact
Delivery Area
Delivery/Return Policy
My Account
Events
Faqs
Our Products
Baby Chicks & Pullets
Farm Animals
Pets
Bulk Products
Christmas Trees
Contact San Jose
945 Lincoln Avenue,
San Jose, California 95126,
United States
orders@ganadofeed.com

(408) 289-8626

Mon-Fri 8:30am - 6:00pm
Sat: 9:00am-5:00pm
Sun: 9:00am-3:00pm

Contact Morgan Hill
433 Vineyard Town Ctr,
Morgan Hill, California 95037,
United States
info@ganadofeed.com

(408) 612-8787

Mon-Fri 9:00am - 7:00pm
Sat: 9:00am-5:00pm
Sun: 9:00am-6:00pm

Copyright © 2026 Ganado Feed & Pet Supplies. All Right Reserved

Privacy Policy | Terms of Use | Delivery/Return Policy | Sitemap


Site by Smack Happy Design

Home
Shop San Jose
Shop Morgan Hill
Hay
Baby Chicks & Pullets
Christmas Trees
About Us
Events
Contact
ARG VARIANT=2
FROM mcr.microsoft.com/vscode/devcontainers/ruby:${VARIANT}

ARG NODE_VERSION="lts/*"
RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"
RUN su vscode -c "/usr/local/rvm/bin/rvm fix-permissions"

# Locale env vars
ENV \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# Install tools
RUN \
  apt update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ack \
  && echo "en_US UTF-8" > /etc/locale.gen \
  && locale-gen en_US.UTF-8
